package jp.example;

import static java.lang.String.*;
import static java.util.Arrays.*;

import java.nio.charset.StandardCharsets;
import java.util.UUID;

import javax.servlet.DispatcherType;
import javax.servlet.FilterChain;
import javax.servlet.annotation.WebFilter;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpFilter;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang3.exception.ExceptionUtils;

import jp.co.future.uroborosql.SqlAgent;
import jp.co.future.uroborosql.UroboroSQL;
import jp.co.future.uroborosql.config.SqlConfig;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;

/**
 * Servlet JSP 単一レイヤーアーキテクチャーコントローラーのサンプルです。<br>
 * サンプルは、以下のポリシーに基づいています。
 * <ul>
 * <li>できるだけ純粋な Servlet API と JSP JSTL。DB アクセスは簡単操作が可能な uroboroSQL。
 * <li>シンプルな単一レイヤー: 分散開発や分散実行が不要なプロジェクト向けです。
 * <li>トランザクション操作不要: DB コネクションの取得・解放やロールバックは、このクラスが行います。
 * <li>入力チェックは何でもいいので例外スローするだけ: とりあえず valid メソッドなどで例外スローすれば、message 属性にセットされます。
 * <li>自動 CSRF チェック: Cookie ベースのため、JSP や各サーブレット側では二重送信や CSRF の考慮は不要です。
 * </ul>
 * @author Generated by Pleiades All in One New Gradle Project Wizard (EPL)
 */
@WebFilter("/*")
@Slf4j
public class SingleTierController extends HttpFilter {
	
	/**
	 * @return カレントスレッドの DAO インスタンス
	 * <pre>
	 * 自動採番の主キーを持つテーブは、id などのエンティティに関するアノテーションは不要です。
	 * スネークケース、キャメルケースは自動変換されます。ただし、バインドパラメータ名は変換されません。
	 * <a href="https://future-architect.github.io/uroborosql-doc/why_uroborosql/"
	 * >GitHub: uroboroSQL (ウロボロスキュール)</a>
	 * </pre>
	 */
	public static SqlAgent dao() {
		return daoThreadLocal.get();
	}
	
	/**
	 * 入力チェックなどの正当性をチェックし、不正な場合は指定したメッセージを持つ例外をスローします。
	 * @param isValid 正しい場合は true
	 * @param message 上記が false の時に例外がスローされ、リクエスト属性に "message" としてセットされます。
	 * @param args メッセージの %s や %d に String#format で埋め込む文字列
	 */
	public static void valid(boolean isValid, String message, Object... args) {
		if (!isValid) {
			throw new IllegalStateException(String.format(message, args));
		}
	}
	
	//-------------------------------------------------------------------------
	
	/** カレントスレッドのトランザクション境界内で DAO インスタンスを保持 */
	private static final ThreadLocal<SqlAgent> daoThreadLocal = new ThreadLocal<>();
	
	/** DAO 接続設定 */
	private SqlConfig daoConfig;

	/** Servlet 呼び出し前後のフィルター処理 */
	@Override @SneakyThrows
	protected void doFilter(HttpServletRequest req, HttpServletResponse res, FilterChain chain) {
		req.setCharacterEncoding(StandardCharsets.UTF_8.name());
		HttpSession session = req.getSession();

		// 二重送信や CSRF は処理を中断してトップ画面にリダイレクト
		final String CSRF_NAME = "_csrf";
		String sesCsrf = (String) session.getAttribute(CSRF_NAME);
		String reqCsrf = stream(req.getCookies()).filter(e -> e.getName().equals(CSRF_NAME)).map(Cookie::getValue).findAny().orElse(null);
		String newCsrf = UUID.randomUUID().toString();
		session.setAttribute(CSRF_NAME, newCsrf); // Servlet API 5.1 未満の Cookie は SameSite 未対応のため直書き
		res.addHeader("Set-Cookie", format("%s=%s; %sHttpOnly; SameSite=Strict",CSRF_NAME, newCsrf, req.isSecure() ? "Secure; " : ""));
		
		if ("POST".equals(req.getMethod()) && reqCsrf != null && !reqCsrf.equals(sesCsrf)) {
			req.setAttribute("message", "二重送信または不正なリクエストを無視しました。");
			res.sendRedirect(".");
			return;
		}

		// DB トランザクションの開始、コミット、ロールバック
		try (SqlAgent dao = daoConfig.agent()) {
			try {
				daoThreadLocal.set(dao);
				super.doFilter(req, res, chain); // 各 Servlet 呼び出し
			}
			// サーブレットで発生したすべての例外に対して以下の処理を行う
			// 1. データベーストランザクションのロールバック
			// 2. ルート例外メッセージをリクエスト属性 "message" にセット (Servlet でリダイレクト前にセットする場合はセッション属性)
			// 3. 呼び出し元画面にフォワード (Servlet 側でセットした "jspPath"、セットされていない場合は最後にフォワードされた JSP) 
			catch (Exception e) {
				dao.rollback();
				Throwable cause = ExceptionUtils.getRootCause(e);
				if (!(cause instanceof IllegalStateException)) {
					log.error(e.getMessage(), e);
				}
				req.setAttribute("message", cause.getMessage());
				req.getRequestDispatcher((String) req.getSession().getAttribute("jspPath")).forward(req, res);
			}
		}
	}

	/** Servlet フィルター初期化時のデータベース接続情報と初期データの設定 */
	@Override @SneakyThrows
	public void init() {
		Class.forName("org.h2.Driver");
		daoConfig = UroboroSQL.builder("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1", "sa", "").build();
		try (SqlAgent dao = daoConfig.agent()) {
			dao.updateWith("""
					CREATE TABLE item (
						id INT AUTO_INCREMENT, name VARCHAR(30), release_date CHAR(10), face_auth BOOLEAN,
						PRIMARY KEY (id)
					);
					INSERT INTO item (name, release_date, face_auth) VALUES 
						('iPhone 13 Pro Docomo版','2022-09-11',true),
						('iPhone 13 Pro Max Docomo版','2022-12-05',true),
						('Xperia 1 IV 国内版','2022-07-22',false)
					;
				""").count();
		}
	}

	/** 最後にフォーワードした JSP を保存するフィルター */
	@WebFilter(urlPatterns = "*.jsp", dispatcherTypes = DispatcherType.FORWARD)
	public static class ForwardJspPathSaveFilter extends HttpFilter {
		
		@Override @SneakyThrows
		protected void doFilter(HttpServletRequest req, HttpServletResponse res, FilterChain chain) {
			req.getSession().setAttribute("jspPath", req.getServletPath());
			super.doFilter(req, res, chain);
		}
	}
}
